{% set version = "0.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-vip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vip/vip_{{ version }}.tar.gz
  sha256: 5565dd2895e7166199da859b346bd8fe9c4b48b0871fa799065f9132be780759

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foreach
    - r-ggplot2 >=0.9.0
    - r-tibble
    - r-yardstick
  run:
    - r-base
    - r-foreach
    - r-ggplot2 >=0.9.0
    - r-tibble
    - r-yardstick

test:
  commands:
    - $R -e "library('vip')"           # [not win]
    - "\"%R%\" -e \"library('vip')\""  # [win]

about:
  home: https://koalaverse.github.io/vip/index.html, https://github.com/koalaverse/vip/
  license: GPL-2.0-or-later
  summary: A general framework for constructing variable importance plots from  various types of machine learning models in R. Aside from some standard model- specific variable importance measures, this package also provides model- agnostic approaches that can be applied to any supervised learning algorithm. These include
    an efficient permutation-based variable importance measure as  well as novel approaches based on partial dependence plots (PDPs) and  individual conditional expectation (ICE) curves which are described in  Greenwell et al. (2018) <arXiv:1805.04755>. An experimental method for  quantifying the relative strength of interaction
    effects is also included (see  the previous reference for details).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy

# Package: vip
# Type: Package
# Title: Variable Importance Plots
# Version: 0.1.3
# Authors@R: c( person("Brandon", "Greenwell",  email = "greenwell.brandon@gmail.com", role = c("aut", "cre"),  comment = c(ORCID = "0000-0002-8120-0084")), person("Brad", "Boehmke", email = "bradleyboehmke@gmail.com", role = c("aut"), comment = c(ORCID = "0000-0002-3611-8516")), person("Bernie", "Gray", email = "bfgray3@gmail.com", role = c("aut"), comment = c(ORCID = "0000-0001-9190-6032")) )
# Description: A general framework for constructing variable importance plots from  various types of machine learning models in R. Aside from some standard model- specific variable importance measures, this package also provides model- agnostic approaches that can be applied to any supervised learning algorithm. These include an efficient permutation-based variable importance measure as  well as novel approaches based on partial dependence plots (PDPs) and  individual conditional expectation (ICE) curves which are described in  Greenwell et al. (2018) <arXiv:1805.04755>. An experimental method for  quantifying the relative strength of interaction effects is also included (see  the previous reference for details).
# License: GPL (>= 2)
# URL: https://koalaverse.github.io/vip/index.html, https://github.com/koalaverse/vip/
# BugReports: https://github.com/koalaverse/vip/issues
# Encoding: UTF-8
# LazyData: true
# Imports: ggplot2 (>= 0.9.0), gridExtra, magrittr, ModelMetrics, pdp, plyr, stats, tibble, utils
# Suggests: DT, C50, caret, Ckmeans.1d.dp, covr, Cubist, doParallel, dplyr, earth, gbm, glmnet, h2o, htmlwidgets, keras, knitr, lattice, mlbench, neuralnet, NeuralNetTools, nnet, party, partykit, randomForest, ranger, rmarkdown, rpart, RSNNS, sparkline, sparklyr, testthat, varImp, xgboost
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-03 11:49:53 UTC; b780620
# Author: Brandon Greenwell [aut, cre] (<https://orcid.org/0000-0002-8120-0084>), Brad Boehmke [aut] (<https://orcid.org/0000-0002-3611-8516>), Bernie Gray [aut] (<https://orcid.org/0000-0001-9190-6032>)
# Maintainer: Brandon Greenwell <greenwell.brandon@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-03 14:20:02 UTC
