appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Dqi3Iip9Hefdo+yFyJyobUPzP+QU6ge/E+sO/08FJA04bn9dgCn8qaHw9sqaTmJilfJFygOh6Ou50axRi1Z7fJI8GUvGxbItXZHXnXC3Dd7vobAKWnbsvmKsvIdxACP/v7vxSBdulumsuF5XVj0IozPtQ1OH3JYow/Ekc70SjhF9UKel5CpW3aq60bt4w8cq3rU96pCkp6cI4FTcQkuJl8UsfYel/xZkUP/gH3s7SJz2YhvAGuGz/BEMoqivJGDYxUHXTrKUmbNsnSEwJJL9XeQh0ZsKMuVqMOyfZLAiKSGPrOV881ZW8IhwObhhgao6pIGHjBipL5qgD8gnzZHizh1Li3JEsDV6J1dSR4O9YyJe6J5945VLMS1lzRBMj5VI7aeDJJsXnenqYRCZgzxUaUFln5iqvPbBiev23KFxTv+ZcKCimQ+WSDoH3XDCwvQbPKGt6P4FD8XtBQ4/Y1KmJiuCiC3cjI2rh1zaSHIEbWkcV+P8/lUI7A+dMGhEemS3wk0r2SYX1vejLWYItwuZo4Wz/F4Yc18fl8hXDnm59ZFWrTKGnH1tfH+U5H+1wMjoCac5drDjQcT0MX9m3HNag/G8jzrx1S2ktcX2ONLPMqMc11tgfKI3UytDXF7i+tgkoMvgAHa+zhGRRYc9y9fOT2XttFhJouFPHObKvqNPGYI=
conda_forge_output_validation: false
